# Generated by Django 4.0.6 on 2022-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dados_pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='pokemon', verbose_name='Imagem')),
                ('number', models.IntegerField(verbose_name='Número')),
            ],
        ),
    ]
