# Generated by Django 4.0.6 on 2022-08-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='pokemon', verbose_name='Imagem')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('abilities', models.CharField(max_length=100, verbose_name='Habilidades')),
                ('evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pokemon', verbose_name='Evolução')),
            ],
        ),
        migrations.DeleteModel(
            name='dados_pokemon',
        ),
    ]
